// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"compiler/token"
)

const (
	NoState    = -1
	NumStates  = 71
	NumSymbols = 91
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '_'
1: '.'
2: '"'
3: '"'
4: 'p'
5: 'r'
6: 'o'
7: 'g'
8: 'r'
9: 'a'
10: 'm'
11: ';'
12: 'm'
13: 'a'
14: 'i'
15: 'n'
16: 'e'
17: 'n'
18: 'd'
19: 'v'
20: 'a'
21: 'r'
22: ':'
23: ','
24: 'i'
25: 'n'
26: 't'
27: 'f'
28: 'l'
29: 'o'
30: 'a'
31: 't'
32: '{'
33: '}'
34: 'p'
35: 'r'
36: 'i'
37: 'n'
38: 't'
39: '('
40: ')'
41: '='
42: 'w'
43: 'h'
44: 'i'
45: 'l'
46: 'e'
47: 'd'
48: 'o'
49: 'i'
50: 'f'
51: 'e'
52: 'l'
53: 's'
54: 'e'
55: '>'
56: '<'
57: '!'
58: '='
59: '+'
60: '-'
61: '*'
62: '/'
63: 'v'
64: 'o'
65: 'i'
66: 'd'
67: '['
68: ']'
69: ' '
70: '\t'
71: '\n'
72: '\r'
73: 'a'-'z'
74: 'a'-'z'
75: 'A'-'Z'
76: 'a'-'z'
77: 'A'-'Z'
78: '0'-'9'
79: 'a'-'z'
80: 'A'-'Z'
81: '0'-'9'
82: '0'-'9'
83: '0'-'9'
84: '0'-'9'
85: '0'-'9'
86: '0'-'9'
87: '0'-'9'
88: 'a'-'z'
89: 'A'-'Z'
90: .
*/
