// Code generated by gocc; DO NOT EDIT.

package parser

import (
  "compiler/ast"
  "compiler/types"
  "compiler/memory"
  "compiler/token"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Start	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Start : Programa	<<  >>`,
		Id:         "Start",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program_Create : id	<< ast.CreateFuntion(X[0], true) >>`,
		Id:         "Program_Create",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.CreateFuntion(X[0], true)
		},
	},
	ProdTabEntry{
		String: `Programa : program Program_Create semicolon Vars Programa_PR main Body end	<<  >>`,
		Id:         "Programa",
		NTType:     3,
		Index:      3,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Programa : program Program_Create semicolon Programa_PR main Body end	<<  >>`,
		Id:         "Programa",
		NTType:     3,
		Index:      4,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Programa_PR : Funcs Programa_PR	<<  >>`,
		Id:         "Programa_PR",
		NTType:     4,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Programa_PR : empty	<<  >>`,
		Id:         "Programa_PR",
		NTType:     4,
		Index:      6,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Enqueue_Vars : id	<< ast.AddVarToQueue(X[0]) >>`,
		Id:         "Enqueue_Vars",
		NTType:     5,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AddVarToQueue(X[0])
		},
	},
	ProdTabEntry{
		String: `Declare_Vars : Type	<< ast.AddVarsToTable(X[0].(types.Type)) >>`,
		Id:         "Declare_Vars",
		NTType:     6,
		Index:      8,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AddVarsToTable(X[0].(types.Type))
		},
	},
	ProdTabEntry{
		String: `Vars : var Enqueue_Vars Vars_PR two_dots Declare_Vars semicolon Vars_PR_PR	<<  >>`,
		Id:         "Vars",
		NTType:     7,
		Index:      9,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Vars_PR : comma Enqueue_Vars Vars_PR	<<  >>`,
		Id:         "Vars_PR",
		NTType:     8,
		Index:      10,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Vars_PR : empty	<<  >>`,
		Id:         "Vars_PR",
		NTType:     8,
		Index:      11,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Vars_PR_PR : Enqueue_Vars Vars_PR two_dots Declare_Vars semicolon Vars_PR_PR	<<  >>`,
		Id:         "Vars_PR_PR",
		NTType:     9,
		Index:      12,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Vars_PR_PR : empty	<<  >>`,
		Id:         "Vars_PR_PR",
		NTType:     9,
		Index:      13,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Type : int_rw	<< ast.SetCurrentType(types.Int) >>`,
		Id:         "Type",
		NTType:     10,
		Index:      14,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.SetCurrentType(types.Int)
		},
	},
	ProdTabEntry{
		String: `Type : float_rw	<< ast.SetCurrentType(types.Float) >>`,
		Id:         "Type",
		NTType:     10,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.SetCurrentType(types.Float)
		},
	},
	ProdTabEntry{
		String: `Body : curly_open Body_PR curly_close	<<  >>`,
		Id:         "Body",
		NTType:     11,
		Index:      16,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Body_PR : Statement Body_PR	<<  >>`,
		Id:         "Body_PR",
		NTType:     12,
		Index:      17,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Body_PR : empty	<<  >>`,
		Id:         "Body_PR",
		NTType:     12,
		Index:      18,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Statement : Assign	<< ast.EndExpression() >>`,
		Id:         "Statement",
		NTType:     13,
		Index:      19,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `Statement : Condition	<< ast.EndExpression() >>`,
		Id:         "Statement",
		NTType:     13,
		Index:      20,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `Statement : Cycle	<< ast.EndExpression() >>`,
		Id:         "Statement",
		NTType:     13,
		Index:      21,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `Statement : F_call	<< ast.EndExpression() >>`,
		Id:         "Statement",
		NTType:     13,
		Index:      22,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `Statement : Print	<< ast.EndExpression() >>`,
		Id:         "Statement",
		NTType:     13,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `String_Constant : string	<< ast.PushOperand(memory.AssignStringConstant(X[0].(*token.Token))) >>`,
		Id:         "String_Constant",
		NTType:     14,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperand(memory.AssignStringConstant(X[0].(*token.Token)))
		},
	},
	ProdTabEntry{
		String: `Print_Op : print	<< ast.PushOperator(types.Print) >>`,
		Id:         "Print_Op",
		NTType:     15,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Print)
		},
	},
	ProdTabEntry{
		String: `Print : Print_Op parenthesis_open Expr Print_PR parenthesis_close semicolon	<<  >>`,
		Id:         "Print",
		NTType:     16,
		Index:      26,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Print : Print_Op parenthesis_open String_Constant Print_PR parenthesis_close semicolon	<<  >>`,
		Id:         "Print",
		NTType:     16,
		Index:      27,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Print_PR_Op : comma	<< ast.PushOperator(types.Print) >>`,
		Id:         "Print_PR_Op",
		NTType:     17,
		Index:      28,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Print)
		},
	},
	ProdTabEntry{
		String: `Print_PR : Print_PR_Op Expr Print_PR	<<  >>`,
		Id:         "Print_PR",
		NTType:     18,
		Index:      29,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Print_PR : Print_PR_Op String_Constant Print_PR	<<  >>`,
		Id:         "Print_PR",
		NTType:     18,
		Index:      30,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Print_PR : empty	<<  >>`,
		Id:         "Print_PR",
		NTType:     18,
		Index:      31,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Assign : Id_Index Assign_Operator Exp semicolon	<<  >>`,
		Id:         "Assign",
		NTType:     19,
		Index:      32,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Assign_Operator : equal	<< ast.PushOperator(types.Assign) >>`,
		Id:         "Assign_Operator",
		NTType:     20,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Assign)
		},
	},
	ProdTabEntry{
		String: `Cycle_End : semicolon	<< ast.CyclePopJumpStack() >>`,
		Id:         "Cycle_End",
		NTType:     21,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.CyclePopJumpStack()
		},
	},
	ProdTabEntry{
		String: `Cycle : while GotoF_Generation Expr Parenthesis_Close_Exp do Body Cycle_End	<<  >>`,
		Id:         "Cycle",
		NTType:     22,
		Index:      35,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `GotoF_Generation : parenthesis_open	<< ast.PushOperator(types.GotoF) >>`,
		Id:         "GotoF_Generation",
		NTType:     23,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.GotoF)
		},
	},
	ProdTabEntry{
		String: `Goto_Generation : else	<< ast.PopJumpStack(true) >>`,
		Id:         "Goto_Generation",
		NTType:     24,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PopJumpStack(true)
		},
	},
	ProdTabEntry{
		String: `Goto_With_Jump : Goto_Generation	<< ast.PushOperator(types.Goto) >>`,
		Id:         "Goto_With_Jump",
		NTType:     25,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Goto)
		},
	},
	ProdTabEntry{
		String: `Jump_End_With_Skip : semicolon	<< ast.PopJumpStack(true) >>`,
		Id:         "Jump_End_With_Skip",
		NTType:     26,
		Index:      39,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PopJumpStack(true)
		},
	},
	ProdTabEntry{
		String: `Jump_End_Without_Skip : semicolon	<< ast.PopJumpStack(false) >>`,
		Id:         "Jump_End_Without_Skip",
		NTType:     27,
		Index:      40,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PopJumpStack(false)
		},
	},
	ProdTabEntry{
		String: `Parenthesis_Close_Exp : parenthesis_close	<< ast.EndExpression() >>`,
		Id:         "Parenthesis_Close_Exp",
		NTType:     28,
		Index:      41,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.EndExpression()
		},
	},
	ProdTabEntry{
		String: `Condition : if GotoF_Generation Expr Parenthesis_Close_Exp Body Jump_End_Without_Skip	<<  >>`,
		Id:         "Condition",
		NTType:     29,
		Index:      42,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Condition : if GotoF_Generation Expr Parenthesis_Close_Exp Body Goto_With_Jump Body Jump_End_With_Skip	<<  >>`,
		Id:         "Condition",
		NTType:     29,
		Index:      43,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_call : id parenthesis_open parenthesis_close semicolon	<<  >>`,
		Id:         "F_call",
		NTType:     30,
		Index:      44,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_call : id parenthesis_open Expr F_call_PR parenthesis_close semicolon	<<  >>`,
		Id:         "F_call",
		NTType:     30,
		Index:      45,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_call_PR : comma Expr F_call_PR	<<  >>`,
		Id:         "F_call_PR",
		NTType:     31,
		Index:      46,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_call_PR : empty	<<  >>`,
		Id:         "F_call_PR",
		NTType:     31,
		Index:      47,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Cte : myint	<< ast.PushOperand(memory.AssignIntConstant(X[0])) >>`,
		Id:         "Cte",
		NTType:     32,
		Index:      48,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperand(memory.AssignIntConstant(X[0]))
		},
	},
	ProdTabEntry{
		String: `Cte : myfloat	<< ast.PushOperand(memory.AssignFloatConstant(X[0])) >>`,
		Id:         "Cte",
		NTType:     32,
		Index:      49,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperand(memory.AssignFloatConstant(X[0]))
		},
	},
	ProdTabEntry{
		String: `Expr : Exp	<<  >>`,
		Id:         "Expr",
		NTType:     33,
		Index:      50,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Expr : Exp GreaterThan_Operator Exp	<<  >>`,
		Id:         "Expr",
		NTType:     33,
		Index:      51,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Expr : Exp LessThan_Operator Exp	<<  >>`,
		Id:         "Expr",
		NTType:     33,
		Index:      52,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Expr : Exp NotEqual_Operator Exp	<<  >>`,
		Id:         "Expr",
		NTType:     33,
		Index:      53,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term	<<  >>`,
		Id:         "Exp",
		NTType:     34,
		Index:      54,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term Plus_Operator Exp	<<  >>`,
		Id:         "Exp",
		NTType:     34,
		Index:      55,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term Minus_Operator Exp	<<  >>`,
		Id:         "Exp",
		NTType:     34,
		Index:      56,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Fact	<<  >>`,
		Id:         "Term",
		NTType:     35,
		Index:      57,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Fact Mult_Operator Term	<<  >>`,
		Id:         "Term",
		NTType:     35,
		Index:      58,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Fact Div_Operator Term	<<  >>`,
		Id:         "Term",
		NTType:     35,
		Index:      59,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Id_Index : id	<< ast.GetVarIndex(X[0]) >>`,
		Id:         "Id_Index",
		NTType:     36,
		Index:      60,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.GetVarIndex(X[0])
		},
	},
	ProdTabEntry{
		String: `Plus_Operator : plus	<< ast.PushOperator(types.Add) >>`,
		Id:         "Plus_Operator",
		NTType:     37,
		Index:      61,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Add)
		},
	},
	ProdTabEntry{
		String: `Minus_Operator : minus	<< ast.PushOperator(types.Sub) >>`,
		Id:         "Minus_Operator",
		NTType:     38,
		Index:      62,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Sub)
		},
	},
	ProdTabEntry{
		String: `Mult_Operator : mult	<< ast.PushOperator(types.Mul) >>`,
		Id:         "Mult_Operator",
		NTType:     39,
		Index:      63,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Mul)
		},
	},
	ProdTabEntry{
		String: `Div_Operator : div	<< ast.PushOperator(types.Div) >>`,
		Id:         "Div_Operator",
		NTType:     40,
		Index:      64,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.Div)
		},
	},
	ProdTabEntry{
		String: `GreaterThan_Operator : greater_than	<< ast.PushOperator(types.GreaterThan) >>`,
		Id:         "GreaterThan_Operator",
		NTType:     41,
		Index:      65,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.GreaterThan)
		},
	},
	ProdTabEntry{
		String: `LessThan_Operator : less_than	<< ast.PushOperator(types.LessThan) >>`,
		Id:         "LessThan_Operator",
		NTType:     42,
		Index:      66,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.LessThan)
		},
	},
	ProdTabEntry{
		String: `NotEqual_Operator : not_equal	<< ast.PushOperator(types.NotEqual) >>`,
		Id:         "NotEqual_Operator",
		NTType:     43,
		Index:      67,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.NotEqual)
		},
	},
	ProdTabEntry{
		String: `Negative_Operator : minus	<< memory.MakeOperandNegative() >>`,
		Id:         "Negative_Operator",
		NTType:     44,
		Index:      68,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return memory.MakeOperandNegative()
		},
	},
	ProdTabEntry{
		String: `Fact_Open_Divider : parenthesis_open	<< ast.PushOperator(types.StackDivider) >>`,
		Id:         "Fact_Open_Divider",
		NTType:     45,
		Index:      69,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.PushOperator(types.StackDivider)
		},
	},
	ProdTabEntry{
		String: `Fact_Close_Divider : parenthesis_close	<< ast.CloseFakeStack() >>`,
		Id:         "Fact_Close_Divider",
		NTType:     46,
		Index:      70,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.CloseFakeStack()
		},
	},
	ProdTabEntry{
		String: `Fact : Fact_Open_Divider Expr Fact_Close_Divider	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      71,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : Cte	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      72,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : Id_Index	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      73,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : plus Id_Index	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      74,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : Negative_Operator Id_Index	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      75,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : plus Cte	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      76,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Fact : Negative_Operator Cte	<<  >>`,
		Id:         "Fact",
		NTType:     47,
		Index:      77,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Func_Create : id	<< ast.CreateFuntion(X[0], false) >>`,
		Id:         "Func_Create",
		NTType:     48,
		Index:      78,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.CreateFuntion(X[0], false)
		},
	},
	ProdTabEntry{
		String: `Func_Close : semicolon	<< ast.ResetToGlobalScope() >>`,
		Id:         "Func_Close",
		NTType:     49,
		Index:      79,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.ResetToGlobalScope()
		},
	},
	ProdTabEntry{
		String: `Funcs : void Func_Create parenthesis_open parenthesis_close bracket_open Body bracket_close Func_Close	<<  >>`,
		Id:         "Funcs",
		NTType:     50,
		Index:      80,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Funcs : void Func_Create parenthesis_open parenthesis_close bracket_open Vars Body bracket_close Func_Close	<<  >>`,
		Id:         "Funcs",
		NTType:     50,
		Index:      81,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Funcs : void Func_Create parenthesis_open Enqueue_Vars two_dots Declare_Vars Funcs_PR parenthesis_close bracket_open Body bracket_close Func_Close	<<  >>`,
		Id:         "Funcs",
		NTType:     50,
		Index:      82,
		NumSymbols: 12,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Funcs : void Func_Create parenthesis_open Enqueue_Vars two_dots Declare_Vars Funcs_PR parenthesis_close bracket_open Vars Body bracket_close Func_Close	<<  >>`,
		Id:         "Funcs",
		NTType:     50,
		Index:      83,
		NumSymbols: 13,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Funcs_PR : comma Enqueue_Vars two_dots Declare_Vars Funcs_PR	<<  >>`,
		Id:         "Funcs_PR",
		NTType:     51,
		Index:      84,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Funcs_PR : empty	<<  >>`,
		Id:         "Funcs_PR",
		NTType:     51,
		Index:      85,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
}
